version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db

volumes:
  pgdata:
